project_id = "ewymvxhpkswhsirdrjub"

[functions.widget-api]
verify_jwt = false

[functions.test-integration]
verify_jwt = true

[functions.webhook-shopify]
verify_jwt = false

[functions.webhook-stripe]
verify_jwt = false

[functions.admin-user-actions]
verify_jwt = true

[functions.system-metrics]
verify_jwt = true

[functions.resend-confirmation]
verify_jwt = true

[functions.send-team-invitation]
verify_jwt = true

[functions.sync-google-reviews]
verify_jwt = true

[functions.sync-instagram]
verify_jwt = true

[functions.sync-twitter]
verify_jwt = true

[functions.load-test]
verify_jwt = true
